language: php
dist: jessie
sudo: false
notifications:
  email: false

php:
  - 7.0

addons:
  ssh_known_hosts: ndi.iteam.org

before_script:
  - cd app
  - composer install
script:
  - echo "todo"

before_deploy:
  - cd ..
  - ls -la
  - openssl aes-256-cbc -K $encrypted_33b04ab955c1_key -iv $encrypted_33b04ab955c1_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scp ./scripts/deploy.sh debian@ndi.iteam.org:~ && ssh debian@ndi.iteam.org "chmod +x ./deploy.sh && ./deploy.sh"
  on:
    branch:
      - master
      - travis
